### ISSUE TITLE
what is argsLength in your parsed object

### ISSUE THREAD

**Issue by saltphish** [nrjais/cmd-line-args-parser#2]
```javascript
{
    flags: [],
    options: {
      n: 10
    },
    argsLength : 'single',
    arguments: ["toDo.txt"]
  }
```
how it is useful in implementing command #

**Comment by nrjais** [comment]
It gives how many arguments were passed
 for 0 : 'noArgs'
      1  :  'single'
    >2 : 'multiple'

**Comment by saltphish** [comment]
halndling numbers is better than strings #
